# GHOST — Générateur de rapport

from datetime import datetime
import json
import os


def generate_report(target: str, results: list, report_type: str = "markdown") -> str:
    """Generate OSINT report from results"""

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    date_str = datetime.now().strftime("%Y%m%d_%H%M%S")

    found = [r for r in results if r.get("exists")]
    not_found = [r for r in results if not r.get("exists") and r.get("error") is None]
    errors = [r for r in results if r.get("error")]

    if report_type == "json":
        report_data = {
            "tool": "GHOST",
            "target": target,
            "timestamp": timestamp,
            "summary": {
                "total_checked": len(results),
                "found": len(found),
                "not_found": len(not_found),
                "errors": len(errors),
            },
            "results": results,
        }
        report_dir = os.path.join(os.path.dirname(__file__), "../../reports")
        os.makedirs(report_dir, exist_ok=True)
        filepath = os.path.join(report_dir, f"ghost_{target}_{date_str}.json")
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(report_data, f, indent=2, ensure_ascii=False, default=str)
        return filepath

    # === MARKDOWN REPORT ===
    report = f"""# 👻 GHOST Report — `{target}`

**Generated:** {timestamp}
**Target:** `{target}`
**Profiles found:** {len(found)}/{len(results)}

---

## 🎯 Résumé

| Métrique | Valeur |
|---|---|
| Plateformes vérifiées | {len(results)} |
| ✅ Profils trouvés | {len(found)} |
| ❌ Non trouvés | {len(not_found)} |
| ⚠️ Erreurs/Blocks | {len(errors)} |

"""

    if found:
        report += "\n## 🔴 PROFILS TROUVÉS\n\n"
        report += "| Plateforme | URL | Données |\n"
        report += "|---|---|---|\n"
        for r in found:
            platform = r.get("platform", "Unknown")
            url = r.get("url", "")
            data_preview = str(r.get("data", ""))[:80].replace("\n", " ").replace("|", "\\|")
            report += f"| **{platform}** | {url} | {data_preview} |\n"

        report += "\n### 📊 Détails\n\n"
        for r in found:
            platform = r.get("platform", "Unknown")
            report += f"\n#### {platform}\n"
            report += f"- URL: {r.get('url', '')}\n"
            if r.get("data"):
                for key, val in r["data"].items():
                    if val and val != "N/A":
                        report += f"- **{key}**: {val}\n"
            report += "\n"

    if errors:
        report += "\n## ⚠️ Erreurs/Rate-limited\n\n"
        for r in errors:
            report += f"- {r.get('platform', 'Unknown')}: {r.get('error')}\n"

    report += f"""

---

## 💀 Verdict

"""

    if len(found) > 0:
        report += f"**{len(found)} profil(s) lié(s) à `{target}` trouvé(s). L'anonymat n'est pas absolu.**\n"
    else:
        report += f"Aucun profil trouvé sur {len(results)} plateformes. Le pseudonyme `{target}` est peu réutilisé.\n"
        report += "\n### Suggestions\n"
        report += "- Essayer des variantes du pseudo (avec/sans underscores, chiffres)\n"
        report += "- Reverse image search si photo de profil disponible\n"
        report += "- Vérifier fuites de données avec l'email si connu\n"
        # report += "- Utiliser les API payantes (DeHashed, Spytox) pour plus de données\n"

    report += f"\n---\n*Generated by GHOST v0.1*\n"

    # Save report
    report_dir = os.path.join(os.path.dirname(__file__), "../../reports")
    os.makedirs(report_dir, exist_ok=True)
    filepath = os.path.join(report_dir, f"ghost_{target}_{date_str}.md")
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(report)

    return filepath